### ISSUE TITLE
Calculator vulnerabilities

### ISSUE THREAD

**Issue by EmilisEm** [rhssh/py-calc#1]
eval() funkciją galima naudoti ne tik paprastai aritmetikai atlikti, bet ir vykdyti kitas programoje esančias funkcijas.
Dabar programa maža, bet ,jeigu išsiplėstų jos funkcijos, ji taptu nusaugi. Tarkim naudotum os library saugant skaičiavimus faile, kad programa turėtų atmintį. Tada vartotojas galetų įrašyti __file__ ir sužinojęs direktoriją ištrinti tavo programą (__file__ jau dabar veikia. Parašo einamąjį failą).
Naudingesnis darbas būtų sukurti savo parserį, kuris skaitydamas visą eilutę kaip String duomenų tipą ją išskaido i atskirus aritmetinius veiksmus ir juos atlieka.

**Comment by rhssh** [comment]
@EmilisEm dalykas toks, nelabai galvoju plėst šito. čia tik buvo testas iš kiek žinau python :Dd
